PImage hPipeBody;
PImage hPipeCage;
PImage vPipeBody;
PImage vPipeCage;
PImage neCurveBody;
PImage neCurveCage;
PImage nwCurveBody;
PImage nwCurveCage;
PImage seCurveBody;
PImage seCurveCage;
PImage swCurveBody;
PImage swCurveCage;
PImage xNTBody;
PImage xNTCage;
PImage xETBody;
PImage xETCage;
PImage xSTBody;
PImage xSTCage;
PImage xWTBody;
PImage xWTCage;
PImage crossBody;
PImage crossCage;
PImage arrow;
PImage bBrine;
PImage nInserter1;
PImage nInserter2;
PImage nInserter3;
PImage eInserter1;
PImage eInserter2;
PImage eInserter3;
PImage sInserter1;
PImage sInserter2;
PImage sInserter3;
PImage wInserter1;
PImage wInserter2;
PImage wInserter3;
PImage logo;



void imgLoad() {
  hPipeBody = loadImage("Horizontal Pipe Body.png");
  hPipeCage = loadImage("Horizontal Pipe Cage.png");
  vPipeBody = loadImage("Vertical Pipe Body.png");
  vPipeCage = loadImage("Vertical Pipe Cage.png");
  neCurveBody = loadImage("NE Curve Pipe Body.png");
  neCurveCage = loadImage("NE Curve Pipe Cage.png");
  nwCurveBody = loadImage("NW Curve Pipe Body.png");
  nwCurveCage = loadImage("NW Curve Pipe Cage.png");
  seCurveBody = loadImage("SE Curve Pipe Body.png");
  seCurveCage = loadImage("SE Curve Pipe Cage.png");
  swCurveBody = loadImage("SW Curve Pipe Body.png");
  swCurveCage = loadImage("SW Curve Pipe Cage.png");
  xNTBody = loadImage("!N T Pipe Body.png");
  xNTCage = loadImage("!N T Pipe Cage.png");
  xETBody = loadImage("!E T Pipe Body.png");
  xETCage = loadImage("!E T Pipe Cage.png");
  xSTBody = loadImage("!S T Pipe Body.png");
  xSTCage = loadImage("!S T Pipe Cage.png");
  xWTBody = loadImage("!W T Pipe Body.png");
  xWTCage = loadImage("!W T Pipe Cage.png");
  crossBody = loadImage("Cross Pipe Body.png");
  crossCage = loadImage("Cross Pipe Cage.png");
  arrow = loadImage("Arrow.png");
  bBrine = loadImage("Brackish_Brine.png");
  nInserter1 = loadImage("N Item Inserter F1.png");
  nInserter2 = loadImage("N Item Inserter F2.png");
  nInserter3 = loadImage("N Item Inserter F3.png");
  eInserter1 = loadImage("E Item Inserter F1.png");
  eInserter2 = loadImage("E Item Inserter F2.png");
  eInserter3 = loadImage("E Item Inserter F3.png");
  sInserter1 = loadImage("S Item Inserter F1.png");
  sInserter2 = loadImage("S Item Inserter F2.png");
  sInserter3 = loadImage("S Item Inserter F3.png");
  wInserter1 = loadImage("W Item Inserter F1.png");
  wInserter2 = loadImage("W Item Inserter F2.png");
  wInserter3 = loadImage("W Item Inserter F3.png");
  logo = loadImage("Logo.png");
}
